######################################################################
# Automatically generated by qmake (2.01a) Sat Aug 18 15:17:10 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h ocean.h
SOURCES += main.cpp mainwindow.cpp ocean.cpp
