######################################################################
# Automatically generated by qmake (2.01a) Sat Aug 18 15:03:34 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
